name: ubuntu-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  streaming-cpp-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Env
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ openjdk-8-jdk python3.7 zlib1g-dev zip
            apt-get install git go pip3 maven
            sh scripts/install-bazel.sh

    - name: Prepare format tools
      run: sh -c "bash script/prepare_format_tools.sh"

    - name: Lint and Check
      run: sh -c "bash streaming/buildtest.sh"
