name: ubuntu-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Ubuntu-Lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Env
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ openjdk-8-jdk python3.7 zlib1g-dev zip
            apt-get install -yq git golang-go python3-pip maven
            sh scripts/install-bazel.sh

    - name: Prepare format tools
      run: sh -c "bash scripts/prepare_format_tools.sh"

    - name: Lint and Check
      run: sh -c "bash scripts/format.sh" && sh -c "bash scripts/check-git-format-output.sh"
